### ISSUE TITLE
Species range predictor dies silently and stops entire process when it is not present.

### ISSUE THREAD

**Issue by MaHaWo** [ssciwr/iSparrow#56]
**Describe the bug**
When in the config file 'lat', 'lon' and 'date'  are given the system tries to use the species range predictor model for the loaded analysis model analogously to birdnet. However, if the loaded model does not have one, then the repl seems to swallow the exception and the process silently stalls. 

**To Reproduce**
use for example the following analysis configuration file with the `google_perch_lite` model from birdnet: 
```yml 
Analysis: 
  Recording:
    species_presence_threshold: 0.03
    min_conf: 0.25
    file_check_poll_interval: 1
    lat: 42.5
    lon: -76.45
    date: 24/01/2024
  Model:
    sigmoid_sensitivity: 1.0
    num_threads: 2
    species_list_file: null

  SpeciesPresence: 
    threshold: 0.03
    num_threads: 1
    use_cache: true

  modelname: google_perch_lite
  pattern: ".wav"
  check_time: 1
  delete_recordings: "never"
  model_dir: ~/faunanet/custom_models 

Data: 
  input: ~/faunanet/data
  output: ~/faunanet/output_local
  Preprocessor:
    sample_rate: 32000
    overlap: 0.0
    sample_secs: 3.0
    resample_type: kaiser_fast
```
and observe that the watcher does not react to new incoming files, printing an exception about a not found species range model upon exit.

**Expected behavior**
The repl should give a message when something goes wrong with the species range prediction and recover correctly. 

**machine/OS:
 - OS: independent
